stages:
  - build
  - deploy

checkName:
  stage: build
  script: 
    - bash -c '[ -s groupMembers.txt ]'

# checkReport:
#   stage: deploy
#   script:
#     - bash -c '[ -f report.pdf ]'

images:
  stage: build
  script:
    - docker build --target peer .
    - docker build --target leader .

