version: "3.8"

services:

  leader:
    container_name: url-shortener_leader
    build:
      context: .
      target: base
    ports:
      - 8001:8001

  peer:
    build:
      context: .
      target: base
    depends_on:
      leader:
        condition: service_healthy
    environment:
      LEADER_HOST: leader
    ports:
      - 8001
