version: "3.8"

services:
  leader:
    container_name: url-shortener_leader
    build:
      context: .
      target: base
    ports:
      - 8001:8001
    volumes:
      - ./build:/app/app/build
    command: ["./run.test.sh"]
