version: "3.8"

services:

  leader:
    container_name: url-shortener_leader
    build:
      context: .
      target: leader
    ports:
      - 8001:8001

  peer:
    build:
      context: .
      target: peer
    depends_on:
      leader:
        condition: service_healthy
    ports:
      - 8001

  db_admin:
    build: ./db_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "4321:80"
