version: "3.8"

services:

  leader:
    container_name: url-shortener_leader
    build:
      context: .
      target: base
    volumes:
      - ./app:/app/app
      # - ./volumes/leader/mongo:/data/db
    ports:
      - 8001:8001

  peer:
    build:
      context: .
      target: base
    depends_on:
      leader:
        condition: service_healthy
    environment:
      LEADER_HOST: leader
    volumes:
      - ./app:/app/app
    ports:
      - 8001
  # db-admin:
  #   image: mongo-express:latest
  #   restart: always
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_URL: mongodb://leader:27017/
  #   ports:
  #     - "4321:8081"
  #   logging:
  #     driver: none
