version: "3.8"

services:

  leader:
    container_name: leader
    build: .
    healthcheck:
      test: "[ -f /tmp/registered ]"
      start_period: 10s
      interval: 1s
      timeout: 1s
      retries: 50

  peer:
    build: .
    depends_on:
      leader:
        condition: service_healthy
    command: ["./run.join.sh", "leader"]
